In [5]:
v = list(range(1, 6))
v
2 * v

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [6]:
v
2 * v

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [7]:
x = [60, 70, 80, 90]
print(len(x))
print(x[0])
print(x[1])
print(x[-1])

4
60
70
90


In [8]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a * b
c
print(a)
print(b)
print(c)

[1 2 3]
[4 5 6]
[ 4 10 18]


In [9]:
import numpy as np
a = np.zeros((2,2))
print(a) 

b = np.ones((1,2))
print(b) 

c = np.full((2,2), 7)
print(c) 

d = np.eye(2)
print(d)

e = np.random.random((2))
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[0.50860007 0.09229842]


In [12]:
import numpy as np
a = np. arange(15)
a = a.reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [14]:
import numpy as np
a =  np. array([0,1,2,3,4,5])
print(a)

[0 1 2 3 4 5]


In [15]:
b = np. array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20]
])
print(b)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [16]:
b = np. array([
    [0,1,2,3],
    [10,11,12,13],
    [20,21,22,23],
])
print(b)
print(b.ndim)
print(b.shape)
print(b.dtype)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]
2
(3, 4)
int64


In [18]:
a = np.arange(9).reshape(3,3)
print(a)
print(a[:2,1:], a[:2,1:].shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2]
 [4 5]] (2, 2)


In [2]:
import numpy as np
a = np.arange(15).reshape(3, 5)

In [3]:
import numpy as np
a = np.array([1,2,3,4,5])

In [ ]:
a = np.arrange(9).reshape(3,3)
print(a)
print(a[:2,1:], a[:2,1:].shape)